export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const FECTH_CATEGORIES = 'FECTH_CATEGORIES';
export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const FETCH_ALL_EXERCISES = 'FETCH_ALL_EXERCISES';
